os:
 - linux
 - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  
addons:
  apt:
    packages:
    - xsltproc
    - libxml2-utils

language: bash

script: make tests
    